### PR TITLE
Detailed Explaination about AI

### PR DESCRIPTION
**Pull request by Aditya7024**
hey @its-vikash just added new features About Ai in brief such as
-> A* algorithm
->min-max algorithm
->state space tree
->neural network
->alpha beta purning  
->html color code 
etc....

### CODE REVIEW

**Comment by its-vikash** [comment]
@Aditya7024 Please format your content into markdown file, so that it could look better

**Comment by Aditya7024** [comment]
hay @its-vikash they are already converted in to .md files (Markdown files) please verify them again

**Comment by its-vikash** [comment]
@Aditya7024 You have just putted all the contents (without formatting) in the markdown file. It should have proper headings, categorised content with points etc.

**Comment by Aditya7024** [comment]
hey @its-vikash  sorry for the inconvenience before  , I made the changes you asked for , If it still have problem just let me know please !

**Review by its-vikash — APPROVED** [review]

**Pull request merged**
